// English → Arabic for short strings that repeat across pages (product names, applications, form options).
// Keys must match the English UI text exactly.
const common = {
  // products
  'FMPE Series': 'سلسلة FMPE',
  'FMPP Series': 'سلسلة FMPP',
  'PE Carrier · 70–80% CaCO₃': 'حامل PE · 70–80% CaCO₃',
  'PP Carrier · 70–80% CaCO₃': 'حامل PP · 70–80% CaCO₃',
  'White Masterbatch': 'ماستر باتش أبيض',
  'TiO₂-based · PE & PP': 'أساسه TiO₂ · PE وPP',
  'Black Masterbatch': 'ماستر باتش أسود',
  'Carbon black · UV-stable': 'أسود الكربون · مقاوم للأشعة فوق البنفسجية',
  'Colour Masterbatch': 'ماستر باتش ملوّن',
  'Full colour range · PE & PP': 'طيف لوني كامل · PE وPP',
  'Additive Masterbatch': 'ماستر باتش الإضافات',
  'UV · Slip · Antiblock': 'UV · منزلق · مانع التصاق',
  'Custom Formulation': 'تركيبة مخصصة',
  'Tailored to your spec': 'مصمَّمة وفق مواصفاتك',
  'Not sure yet': 'لست متأكداً بعد',
  // applications
  'Blown Film': 'أفلام النفخ',
  'Cast Film': 'الأفلام المصبوبة',
  'Injection Molding': 'القولبة بالحقن',
  'Injection Moulding': 'القولبة بالحقن',
  'Blow Molding': 'القولبة بالنفخ',
  'Raffia / Woven Bags': 'الرافيا / الأكياس المنسوجة',
  'Non-woven': 'الأقمشة غير المنسوجة',
  'Thermoforming': 'التشكيل الحراري',
  'Pipe & Profile Extrusion': 'بثق المواسير والبروفايلات',
  'Agricultural Film': 'الأفلام الزراعية',
  'Other': 'أخرى',
  // quantities / regions
  '500 kg – 1 MT (trial)': '500 كجم – 1 طن (تجريبي)',
  '1 MT – 5 MT': '1 – 5 طن',
  '5 MT – 20 MT': '5 – 20 طن',
  '20 MT – 50 MT': '20 – 50 طن',
  '50 MT+': 'أكثر من 50 طن',
  'Egypt': 'مصر',
  'Saudi Arabia': 'السعودية',
  'UAE': 'الإمارات',
  'Kuwait': 'الكويت',
  'Jordan': 'الأردن',
  'Turkey': 'تركيا',
  'Poland / Europe': 'بولندا / أوروبا',
  "Other — I'll specify in the message": 'أخرى — سأوضّح في الرسالة',
  // page chrome shared by product & industry pages
  'Products': 'المنتجات',
  'Industries': 'الصناعات',
  'Request a Quote': 'اطلب عرض سعر',
  'View Grades': 'عرض الدرجات',
  'Grade Reference': 'مرجع الدرجات',
  'A Selection of Available Grades': 'مختارات من الدرجات المتاحة',
  'Grade Code': 'رمز الدرجة',
  'Applications': 'التطبيقات',
  'IN-HOUSE MANUFACTURED': 'تصنيع محلي',
  'CORAPLAST DISTRIBUTED': 'موزّع من Coraplast',
  'Made in Egypt': 'صُنع في مصر',
  'MFI': 'مؤشر الانسياب MFI',
  // industries + common tags
  'Packaging & Flexible Film': 'التغليف والأفلام المرنة',
  'Pipes, Fittings & Profiles': 'المواسير والوصلات والبروفايلات',
  'Pipes & Infrastructure': 'المواسير والبنية التحتية',
  'Agriculture': 'الزراعة',
  'Textiles & Fibre': 'المنسوجات والألياف',
  'Textiles & Raffia': 'المنسوجات والرافيا',
  'Wire & Cable': 'الأسلاك والكابلات',
  'Cable & Wire': 'الكابلات والأسلاك',
  'Automotive & Technical': 'السيارات والاستخدامات الفنية',
  'Construction': 'الإنشاءات',
  'Construction & Sheeting': 'الإنشاءات والألواح',
  'Consumer Goods': 'السلع الاستهلاكية',
  'Packaging & Film': 'التغليف والأفلام',
  'FFS Film': 'أفلام FFS',
  'Stretch Wrap': 'أغلفة التمدد',
  'Greenhouse Film': 'أفلام البيوت المحمية',
  'Mulch Film': 'أفلام المالش',
  'Silage Wrap': 'أغلفة السيلاج',
  'Barrier Film': 'أفلام العزل',
  'DPM': 'عزل الرطوبة (DPM)',
  'Geomembrane': 'الأغشية الجيولوجية',
  'Carrier Bags': 'أكياس التسوق',
  'Bin Liners': 'أكياس القمامة',
  'Household Film': 'أفلام منزلية',
}

export default common
