// About, Contact, Distributors and the colour quote form.
const company = {
  // ── shared form strings ──
  'Full name is required.': 'الاسم الكامل مطلوب.',
  'Company name is required.': 'اسم الشركة مطلوب.',
  'Email address is required.': 'البريد الإلكتروني مطلوب.',
  'Enter a valid email.': 'أدخل بريداً إلكترونياً صحيحاً.',
  'Phone number is required.': 'رقم الهاتف مطلوب.',
  'Something went wrong. Please try again or email us directly.': 'حدث خطأ ما. يرجى المحاولة مرة أخرى أو مراسلتنا مباشرة.',
  'Could not send your request. Please email info@blaubatch.com directly.': 'تعذّر إرسال طلبك. يرجى مراسلتنا مباشرة على info@blaubatch.com.',
  'Please fill in all required fields.': 'يرجى ملء جميع الحقول المطلوبة.',
  '💬 Follow up on WhatsApp': '💬 تابع معنا عبر واتساب',
  'Email': 'البريد الإلكتروني',
  'Phone': 'الهاتف',
  'WhatsApp': 'واتساب',
  'Company': 'الشركة',
  'Full Name': 'الاسم الكامل',
  'WhatsApp Us': 'تواصل عبر واتساب',
  'Email Us': 'راسلنا بالبريد',
  'Contact Us': 'اتصل بنا',
  'Contact': 'اتصل بنا',
  'About': 'من نحن',
  'Your name': 'اسمك', 'Company name': 'اسم الشركة', 'you@company.com': 'you@company.com', 'your@company.com': 'your@company.com',
  'Full name': 'الاسم الكامل', 'Your company name': 'اسم شركتك',

  // ── Contact ──
  'Get in Touch': 'تواصل معنا',
  "Let's talk": 'لنتحدث',
  'production.': 'عن إنتاجك.',
  'Request a quote, ask about our product range, or get technical support. We respond to all inquiries within 24 hours.':
    'اطلب عرض سعر، أو استفسر عن مجموعة منتجاتنا، أو احصل على دعم فني. نرد على جميع الاستفسارات خلال 24 ساعة.',
  'Direct Channels': 'قنوات التواصل المباشر',
  'Message us directly': 'راسلنا مباشرة',
  'Response Time': 'وقت الاستجابة',
  'Within 24 business hours': 'خلال 24 ساعة عمل',
  '⏱ Working Hours': '⏱ ساعات العمل',
  'Saturday – Thursday': 'من السبت إلى الخميس',
  '9:00 AM – 5:00 PM': '9:00 صباحاً – 5:00 مساءً',
  'Cairo local time (UTC+2/+3, seasonal)': 'بتوقيت القاهرة (UTC+2/+3 حسب الموسم)',
  'We respond within 24 hours': 'نرد خلال 24 ساعة',
  '— usually much faster during business hours.': '— وغالباً أسرع بكثير خلال ساعات العمل.',
  'Our Locations': 'مواقعنا',
  'Head Office': 'المقر الرئيسي',
  'Factory': 'المصنع',
  'Arkan Plaza, Building 4, 4th Floor, Sheikh Zayed City, Giza, Egypt': 'مبنى أركان بلازا 4، الطابق الرابع، مدينة الشيخ زايد، الجيزة، مصر',
  '79, 6th Industrial Zone, 6th of October City, Giza, Egypt': '79، المنطقة الصناعية السادسة، مدينة السادس من أكتوبر، الجيزة، مصر',

  // ── Colour quote form ──
  'Quote request received.': 'تم استلام طلب عرض السعر.',
  "We'll review your colour requirements and get back to you within 24 hours.": 'سنراجع متطلباتك اللونية ونعاود التواصل معك خلال 24 ساعة.',
  'Colour Needs': 'احتياجاتك اللونية',
  'Carrier Resin': 'الراتنج الحامل',
  'Select carrier...': 'اختر الحامل...',
  'Select application...': 'اختر التطبيق...',
  'Colour Reference': 'المرجع اللوني',
  "e.g. RAL 3020, Pantone 186 C, or describe: 'traffic red'": "مثال: RAL 3020 أو Pantone 186 C أو صف اللون: 'أحمر مرور'",
  'You can also send us a physical sample for matching.': 'يمكنك أيضاً إرسال عيّنة فعلية للمطابقة.',
  'Volume & Requirements': 'الكمية والمتطلبات',
  'Estimated Monthly Volume': 'الكمية الشهرية التقديرية',
  'Select quantity...': 'اختر الكمية...',
  'Country / Region': 'الدولة / المنطقة',
  'Select country...': 'اختر الدولة...',
  'Sample Required?': 'هل تحتاج عيّنة؟',
  'Select...': 'اختر...',
  'Yes — send a colour sample first': 'نعم — أرسلوا عيّنة لونية أولاً',
  'No — go directly to commercial quote': 'لا — انتقلوا مباشرة إلى العرض التجاري',
  'Contact Details': 'بيانات التواصل',
  'WhatsApp / Phone': 'واتساب / الهاتف',
  'Additional Notes': 'ملاحظات إضافية',
  'Any additional colour requirements, certifications needed, or processing notes...': 'أي متطلبات لونية إضافية أو شهادات مطلوبة أو ملاحظات تشغيل...',
  'Submit Quote Request ↗': 'إرسال طلب عرض السعر ↖',
  'We respond within 24 hours · Saturday–Thursday 9AM–5PM Cairo': 'نرد خلال 24 ساعة · من السبت إلى الخميس 9 صباحاً – 5 مساءً بتوقيت القاهرة',
  'CMB-PE (Polyethylene carrier)': 'CMB-PE (حامل بولي إيثيلين)',
  'CMB-PP (Polypropylene carrier)': 'CMB-PP (حامل بولي بروبيلين)',
  'Both PE and PP': 'PE وPP معاً',
  'Not sure — need guidance': 'لست متأكداً — أحتاج إلى إرشاد',
  'Packaging film / bags': 'أفلام التغليف / الأكياس',
  'Blow molding / bottles': 'القولبة بالنفخ / الزجاجات',
  'Under 100 kg / month': 'أقل من 100 كجم / شهرياً',
  '100–500 kg / month': '100–500 كجم / شهرياً',
  '500 kg – 1 MT / month': '500 كجم – 1 طن / شهرياً',
  '1–5 MT / month': '1–5 طن / شهرياً',
  '5+ MT / month': 'أكثر من 5 طن / شهرياً',
  'Libya': 'ليبيا',

  // ── Distributors ──
  'Distributors': 'الموزعون',
  'Where We Operate': 'أين نعمل',
  'MENA Distribution': 'شبكة التوزيع في الشرق الأوسط',
  'Network': 'وشمال أفريقيا',
  'Blau Batch serves plastic manufacturers across Egypt, the Gulf Cooperation Council, the Levant, and selected North African markets — directly and through regional distribution partners.':
    'تخدم بلاو باتش مصنّعي البلاستيك في مصر ودول مجلس التعاون الخليجي وبلاد الشام وأسواق مختارة في شمال أفريقيا — مباشرةً ومن خلال شركاء التوزيع الإقليميين.',
  'Contact for Your Region': 'تواصل بخصوص منطقتك',
  'Become a Distributor': 'كن موزعاً',
  'Regional Coverage': 'التغطية الإقليمية',
  'Markets We Serve': 'الأسواق التي نخدمها',
  'Direct Sales': 'مبيعات مباشرة',
  'Egypt — Direct': 'مصر — مباشرة',
  'All governorates': 'جميع المحافظات',
  'All Egyptian customers are served directly by Blau Batch from our 6th of October City facility. Direct sales, technical support, and logistics coordination.':
    'تخدم بلاو باتش جميع العملاء في مصر مباشرة من مصنعنا بمدينة السادس من أكتوبر. مبيعات مباشرة ودعم فني وتنسيق لوجستي.',
  'Sales & Technical': 'المبيعات والدعم الفني',
  'Available on request': 'متاح عند الطلب',
  'Gulf Cooperation Council': 'مجلس التعاون الخليجي',
  'UAE · Saudi Arabia · Kuwait · Qatar · Bahrain · Oman': 'الإمارات · السعودية · الكويت · قطر · البحرين · عُمان',
  'GCC markets are served through a combination of direct export from Egypt and appointed regional distributors. Contact us for the distributor in your country.':
    'تُخدم أسواق دول الخليج عبر مزيج من التصدير المباشر من مصر وموزعين إقليميين معتمدين. تواصل معنا لمعرفة الموزع في بلدك.',
  'Export Enquiries': 'استفسارات التصدير',
  'Levant': 'بلاد الشام',
  'Jordan · Lebanon · Palestine · Syria (where accessible)': 'الأردن · لبنان · فلسطين · سوريا (حيثما أمكن)',
  'Levant distribution is handled through regional trading partners with local logistics and technical support capability.':
    'يُدار التوزيع في بلاد الشام عبر شركاء تجاريين إقليميين لديهم قدرات لوجستية ودعم فني محلي.',
  'Regional Enquiries': 'الاستفسارات الإقليمية',
  'North Africa': 'شمال أفريقيا',
  'Libya · Tunisia · Algeria · Morocco (selected markets)': 'ليبيا · تونس · الجزائر · المغرب (أسواق مختارة)',
  'North African markets beyond Egypt are served on a project basis. Minimum order quantities apply for export shipments.':
    'تُخدم أسواق شمال أفريقيا خارج مصر على أساس المشاريع. وتنطبق حدود دنيا للكميات على شحنات التصدير.',
  'Our Supply Partner': 'شريكنا في التوريد',
  'Coraplast — Global Reach': 'Coraplast — حضور عالمي',
  'For white, black, colour, and additive masterbatch lines, Blau Batch is the regional distributor for Coraplast — an internationally certified manufacturer with a global distribution footprint and an ISO 9001 / ISO 14001 quality system.':
    'في خطوط الماستر باتش الأبيض والأسود والملوّن والإضافات، تُعدّ بلاو باتش الموزّع الإقليمي لشركة Coraplast — مصنّع حاصل على شهادات دولية وله حضور توزيعي عالمي ونظام جودة ISO 9001 / ISO 14001.',
  'European customers sourcing Coraplast products can be connected directly. Contact us with your product requirements and region.':
    'يمكن ربط العملاء الأوروبيين الراغبين في منتجات Coraplast بها مباشرة. تواصل معنا بمتطلباتك ومنطقتك.',
  'Coraplast European Markets': 'أسواق Coraplast الأوروبية',
  'Germany': 'ألمانيا', 'France': 'فرنسا', 'Italy': 'إيطاليا', 'Spain': 'إسبانيا', 'United Kingdom': 'المملكة المتحدة', 'Poland': 'بولندا',
  'Czech Republic': 'التشيك', 'Hungary': 'المجر', 'Romania': 'رومانيا', 'Bulgaria': 'بلغاريا',
  'Morocco': 'المغرب', 'Algeria': 'الجزائر', 'Iraq': 'العراق',
  'Coraplast Certifications': 'شهادات Coraplast',
  'ISO 9001 · ISO 14001 · REACH compliant · EU 10/2011 food-contact grades available': 'ISO 9001 · ISO 14001 · متوافق مع REACH · درجات ملامسة الأغذية EU 10/2011 متوفرة',
  'Apply Now': 'قدّم الآن',
  'Tell us about your business.': 'حدّثنا عن عملك.',
  "We review every application personally. You'll hear from us within 48 business hours. No automated rejection emails — if we're not the right fit, we'll tell you why.":
    'نراجع كل طلب بأنفسنا. ستصلك ردودنا خلال 48 ساعة عمل. لا رسائل رفض آلية — وإن لم نكن الشريك المناسب فسنخبرك بالسبب.',
  'Our commitment to you': 'التزامنا تجاهك',
  'Response within 48 business hours': 'الرد خلال 48 ساعة عمل',
  'Honest feedback even if we pass': 'ملاحظات صريحة حتى لو اعتذرنا',
  'Your information stays confidential': 'تبقى معلوماتك سرية',
  'No pushy sales follow-up': 'لا متابعات بيعية مُلحّة',
  'Prefer to talk first?': 'تفضّل التحدث أولاً؟',
  '💬 WhatsApp us before applying': '💬 راسلنا على واتساب قبل التقديم',
  'Application received.': 'تم استلام الطلب.',
  "Thank you for applying. We'll review your application and reach out within 48 business hours.": 'شكراً لتقديمك. سنراجع طلبك ونتواصل معك خلال 48 ساعة عمل.',
  'Distributor Application': 'طلب الانضمام كموزّع',
  'Takes about 3 minutes to complete.': 'يستغرق إكماله نحو 3 دقائق.',
  'Company Name': 'اسم الشركة', 'Your Name': 'اسمك', 'Phone / WhatsApp': 'الهاتف / واتساب',
  'Country / Territory': 'الدولة / المنطقة', 'Select your market': 'اختر سوقك',
  'Plastics Sector Focus': 'التخصص في قطاع البلاستيك', 'Primary industry served': 'القطاع الرئيسي الذي تخدمه',
  'Estimated Annual Masterbatch Volume': 'حجم الماستر باتش السنوي التقديري', 'How much do you expect to sell annually?': 'كم تتوقع أن تبيع سنوياً؟',
  'Tell us about your business': 'حدّثنا عن عملك', 'Submit Application ↗': 'إرسال الطلب ↖',
  'Brief description of your company, current supplier relationships, and why you\'re interested in partnering with Blau Batch...':
    'نبذة عن شركتك وعلاقاتك الحالية مع الموردين وسبب اهتمامك بالشراكة مع بلاو باتش...',
  'Film & Flexible Packaging': 'الأفلام والتغليف المرن', 'Woven Bags / Raffia': 'الأكياس المنسوجة / الرافيا', 'Mixed / General Plastics': 'بلاستيك متنوع / عام',
  'Under 10 MT (exploring)': 'أقل من 10 أطنان (استكشاف)', '10 – 30 MT': '10 – 30 طن', '30 – 100 MT': '30 – 100 طن', '100 – 500 MT': '100 – 500 طن', '500 MT+ (high volume)': 'أكثر من 500 طن (حجم كبير)',
  "Other — I'll specify below": 'أخرى — سأوضّح أدناه',

  // ── About ──
  'Our Story': 'قصتنا',
  'Masterbatch, Made': 'ماستر باتش',
  'to a Higher Standard': 'بمعيار أعلى',
  'Egyptian masterbatch manufacturer and regional distributor. We produce filler masterbatch in-house and bring the full Coraplast range to plastics producers across MENA and Europe.':
    'مصنّع ماستر باتش مصري وموزّع إقليمي. ننتج ماستر باتش الحشو داخل مصنعنا ونوفّر مجموعة Coraplast الشاملة لمصنّعي البلاستيك في الشرق الأوسط وشمال أفريقيا وأوروبا.',
  'View Our Products': 'استعرض منتجاتنا',
  'Founded': 'التأسيس', '6th of October City, Egypt': 'مدينة السادس من أكتوبر، مصر',
  'Annual Capacity': 'الطاقة السنوية', 'Tonnes manufactured': 'أطنان مُصنَّعة',
  'Supplier': 'مورّد', 'Full masterbatch spectrum': 'مجموعة الماستر باتش الشاملة',
  '24h': '24 ساعة', 'Turnaround': 'زمن الاستجابة', 'Quote to confirmation': 'من العرض إلى التأكيد',
  'Custom': 'مخصص', 'Colour Matching & Formulation': 'مطابقة الألوان والتركيبات', 'RAL · Pantone · Bespoke': 'RAL · Pantone · حسب الطلب',
  'Support': 'الدعم', 'Pre & post-sales': 'قبل البيع وبعده',
  'How We Operate': 'كيف نعمل', 'Our Four Pillars': 'ركائزنا الأربع',
  'In-House Manufacturing': 'التصنيع الداخلي',
  'Our 6th of October City facility produces FMPE and FMPP Series masterbatch — giving us direct control over raw material selection, compounding, and QC. Every batch is tested for MFI, ash content, colour, and dispersibility before dispatch.':
    'ينتج مصنعنا في مدينة السادس من أكتوبر ماستر باتش سلسلتي FMPE وFMPP — مما يمنحنا تحكماً مباشراً في اختيار المواد الخام والتركيب ومراقبة الجودة. يُختبَر كل دفعة من حيث MFI ومحتوى الرماد واللون وقابلية التشتّت قبل الشحن.',
  'Exclusive Distribution': 'توزيع حصري',
  'For the full product spectrum — white, black, colour, and additive masterbatch — we are the exclusive regional distributor for Coraplast, a globally certified manufacturer operating to ISO 9001 and ISO 14001 standards.':
    'لمجموعة المنتجات الشاملة — الماستر باتش الأبيض والأسود والملوّن والإضافات — نحن الموزّع الإقليمي الحصري لشركة Coraplast، وهي شركة تصنيع حاصلة على شهادات عالمية وتعمل وفق معياري ISO 9001 وISO 14001.',
  'Technical Competence': 'الكفاءة الفنية',
  "Our team brings deep processing knowledge across blown film, raffia, pipe, injection moulding, and extrusion coating lines. We don't just ship pellets — we recommend the right grade and dosage for your specific machine and application.":
    'يمتلك فريقنا معرفة عميقة بالمعالجة في خطوط أفلام النفخ والرافيا والمواسير والقولبة بالحقن وطلاء البثق. لا نكتفي بشحن الحبيبات — بل نوصي بالدرجة والجرعة المناسبتين لآلتك وتطبيقك.',
  'Responsive Partnership': 'شراكة سريعة الاستجابة',
  "We operate as a hands-on partner, not a catalogue supplier. Quick sampling, technical data on request, and direct access to our compounding engineers — without the overhead of a multinational sales structure.":
    'نعمل كشريك عملي لا كمورّد كتالوج. عيّنات سريعة وبيانات فنية عند الطلب وتواصل مباشر مع مهندسي التركيب لدينا — دون تعقيدات هيكل مبيعات متعدد الجنسيات.',
  'Our Journey': 'مسيرتنا', 'Built to Last': 'بُنيت لتدوم',
  'From a focused PE filler masterbatch producer to a full-spectrum masterbatch partner for the MENA region — our growth has been deliberate and technically grounded.':
    'من منتج متخصص في ماستر باتش الحشو (PE) إلى شريك ماستر باتش شامل لمنطقة الشرق الأوسط وشمال أفريقيا — نموّنا مدروس وقائم على أساس فني.',
  'Founded · 2023': 'التأسيس · 2023',
  'Blau Batch established in 6th of October City, Egypt — focusing on PE filler masterbatch production for the regional film and packaging sector.':
    'تأسست بلاو باتش في مدينة السادس من أكتوبر بمصر — مع التركيز على إنتاج ماستر باتش الحشو (PE) لقطاع الأفلام والتغليف الإقليمي.',
  'Manufacturing': 'التصنيع',
  'In-house compounding line commissioned. FMPE and FMPP Series (70–80% CaCO₃) both launched from day one — covering PE and PP carrier systems for film, raffia, and injection moulding applications.':
    'تشغيل خط التركيب الداخلي. أُطلقت سلسلتا FMPE وFMPP (70–80% CaCO₃) منذ اليوم الأول — لتغطية أنظمة الحوامل PE وPP لتطبيقات الأفلام والرافيا والقولبة بالحقن.',
  'Distribution': 'التوزيع',
  'Partnership established with Coraplast for regional distribution of white, black, colour, and additive masterbatch product lines across MENA.':
    'إبرام شراكة مع Coraplast للتوزيع الإقليمي لخطوط منتجات الماستر باتش الأبيض والأسود والملوّن والإضافات في الشرق الأوسط وشمال أفريقيا.',
  'Expansion': 'التوسع',
  'Customer base extended into Gulf Cooperation Council markets and the Levant. Export logistics established to serve clients across Egypt, Saudi Arabia, UAE, and Jordan.':
    'اتسعت قاعدة العملاء لتشمل أسواق مجلس التعاون الخليجي وبلاد الشام. وأُرسيت خدمات التصدير اللوجستية لخدمة العملاء في مصر والسعودية والإمارات والأردن.',
  'Today': 'اليوم',
  'Serving plastic manufacturers across Egypt, Gulf Cooperation Council markets, and the Levant — with ambitions to expand into European distribution channels.':
    'نخدم مصنّعي البلاستيك في مصر وأسواق مجلس التعاون الخليجي وبلاد الشام — وطموحنا التوسع في قنوات التوزيع الأوروبية.',
  'Purpose': 'الغاية', 'Mission & Vision': 'الرسالة والرؤية', 'Our Mission': 'رسالتنا',
  'One Partner for Every Grade Your Production Needs': 'شريك واحد لكل درجة يحتاجها إنتاجك',
  'To be the most reliable masterbatch partner for plastics processors across MENA and Europe — delivering consistent quality, technical expertise, and the full product spectrum through a single, accountable relationship.':
    'أن نكون شريك الماستر باتش الأكثر موثوقية لمصنّعي البلاستيك في الشرق الأوسط وشمال أفريقيا وأوروبا — بجودة ثابتة وخبرة فنية ومجموعة منتجات شاملة عبر علاقة واحدة مسؤولة.',
  'Our Vision': 'رؤيتنا',
  'The Reference Masterbatch Supplier in the MENA Region': 'المورّد المرجعي للماستر باتش في المنطقة',
  "To grow into the region's reference manufacturer and distributor — recognised not just for product range, but for technical depth, supply reliability, and the long-term partnerships we build with processors at every scale.":
    'أن ننمو لنصبح المصنّع والموزّع المرجعي في المنطقة — معروفين لا بتنوع منتجاتنا فحسب، بل بعمقنا الفني وموثوقية إمداداتنا وشراكاتنا طويلة الأمد مع المصنّعين بمختلف أحجامهم.',
  'What We Stand For': 'ما نؤمن به', 'Our Commitments': 'التزاماتنا',
  'Consistency': 'الثبات',
  "Every batch meets the same specification. Our QC process exists so your process doesn't have to compensate for ours.":
    'كل دفعة تلبّي المواصفات نفسها. وُجدت عملية مراقبة الجودة لدينا كي لا تضطر عمليتك إلى تعويض أي تفاوت في عمليتنا.',
  'Transparency': 'الشفافية',
  'Full traceability from raw material intake to dispatch. TDS and CoA available on request for every shipment.':
    'تتبّع كامل من استلام المواد الخام حتى الشحن. TDS وCoA متاحتان عند الطلب لكل شحنة.',
  'Technical Depth': 'العمق الفني',
  'We understand your machine, not just our product. Grade selection and dosage advice are part of the service.':
    'نفهم آلتك لا منتجنا فقط. فاختيار الدرجة والنصيحة بشأن الجرعة جزء من خدمتنا.',
  'Work With Us': 'اعمل معنا', 'Ready to discuss your requirements?': 'هل أنت مستعد لمناقشة متطلباتك؟',
  "Tell us about your process, your polymer, and your target application. We'll respond within 24 hours.":
    'أخبرنا عن عمليتك والبوليمر المستخدم والتطبيق المستهدف. وسنرد خلال 24 ساعة.',
  'Find a Distributor': 'ابحث عن موزّع',
}

export default company
