// Sustainability, Compare, Resources and the Full Range campaign page.
const pagesExtra = {
  // ───────── Sustainability ─────────
  'ESG & ENVIRONMENT': 'الحوكمة البيئية والاجتماعية',
  'Responsible Masterbatch': 'ماستر باتش مسؤول',
  'For a Circular Economy': 'من أجل اقتصاد دائري',
  'European and global buyers increasingly require verifiable ESG commitments. Blau Batch delivers fully compliant, recyclable masterbatch formulations backed by certified environmental management practices.':
    'يطلب المشترون الأوروبيون والعالميون التزامات ESG يمكن التحقق منها بشكل متزايد. تقدّم بلاو باتش تركيبات ماستر باتش مطابقة تماماً وقابلة لإعادة التدوير، مدعومة بممارسات إدارة بيئية معتمدة.',
  'Request Compliance Docs': 'اطلب وثائق المطابقة',
  'View Certifications': 'عرض الشهادات',
  'Our Approach': 'نهجنا',
  'Three Pillars of Responsible Production': 'ثلاث ركائز للإنتاج المسؤول',
  'Our environmental programme covers the full production lifecycle — from raw material selection through manufacturing, packaging, and end-of-life recyclability of the final plastic article.':
    'يغطي برنامجنا البيئي دورة الإنتاج بأكملها — من اختيار المواد الخام مروراً بالتصنيع والتعبئة، وصولاً إلى قابلية إعادة تدوير المنتج البلاستيكي النهائي في نهاية عمره.',
  'Environmental Commitment': 'الالتزام البيئي',
  'ISO 14001:2015 certified environmental management system': 'نظام إدارة بيئية معتمد وفق ISO 14001:2015',
  'Continuous reduction of production waste and energy consumption': 'خفض مستمر لهدر الإنتاج واستهلاك الطاقة',
  'Responsible raw material sourcing from verified supply chains': 'توريد مسؤول للمواد الخام من سلاسل إمداد موثَّقة',
  'Factory water recycling and zero-liquid-discharge practices': 'إعادة تدوير المياه في المصنع وممارسات التصريف السائل الصفري',
  'Waste Reduction Practices': 'ممارسات خفض الهدر',
  'In-process regrind integration — production trim is reincorporated, not discarded': 'إعادة دمج المطحون داخل العملية — يُعاد استخدام مخلفات الإنتاج بدلاً من التخلص منها',
  'Closed-loop packaging — return programs for 500 kg FIBCs': 'تعبئة بدورة مغلقة — برامج استرجاع لأكياس FIBC سعة 500 كجم',
  'Batch optimisation to minimise purging and colour changeover waste': 'تحسين التشغيلات لتقليل هدر التنظيف وتغيير الألوان',
  'Lean production scheduling to eliminate overrun and dead stock': 'جدولة إنتاج رشيقة للحدّ من الإنتاج الزائد والمخزون الراكد',
  'Recyclable & Compliant Formulations': 'تركيبات قابلة لإعادة التدوير ومطابقة للمواصفات',
  'Mono-material masterbatch grades for HDPE and PP recyclate streams': 'درجات ماستر باتش أحادية المادة لمسارات إعادة تدوير HDPE وPP',
  'Food-contact grades meeting EU Regulation 10/2011 and FDA 21 CFR': 'درجات ملامسة الأغذية المطابقة للائحة الاتحاد الأوروبي 10/2011 وFDA 21 CFR',
  'Heavy-metal-free pigment systems — no cadmium, lead, or chromate VI': 'أنظمة أصباغ خالية من المعادن الثقيلة — دون كادميوم أو رصاص أو كرومات سداسية',
  'Halogen-free flame retardant masterbatch for cable and electronic applications': 'ماستر باتش مثبّط لهب خالٍ من الهالوجين لتطبيقات الكابلات والإلكترونيات',
  'ISO 14001': 'ISO 14001',
  'Environmental Management': 'الإدارة البيئية',
  'Heavy-metal\nfree': 'خالٍ من\nالمعادن الثقيلة',
  'All pigment systems': 'جميع أنظمة الأصباغ',
  'Halogen\nfree': 'خالٍ من\nالهالوجين',
  'Flame retardant grades': 'درجات مثبّطات اللهب',
  'EU 10/2011': 'EU 10/2011',
  'Food-contact compliance': 'مطابقة ملامسة الأغذية',
  'For European Buyers': 'للمشترين الأوروبيين',
  'ESG Compliance You Can Document': 'مطابقة ESG قابلة للتوثيق',
  'European importers face increasing pressure under the CSRD, REACH, and packaging regulations. We supply full compliance documentation with every shipment — CoA, TDS, SVHC declarations, and material safety data — so your procurement and ESG teams can close quickly.':
    'يواجه المستوردون الأوروبيون ضغوطاً متزايدة بموجب CSRD وREACH وتشريعات التغليف. نوفّر وثائق مطابقة شاملة مع كل شحنة — CoA وTDS وإقرارات SVHC وبيانات سلامة المواد — لتتمكن فرق المشتريات وESG لديكم من إنجاز الاعتماد بسرعة.',
  'Our food-contact and recyclable grades are engineered to meet EU circular economy targets, with mono-material formulations that support sortation and mechanical recycling.':
    'صُمّمت درجاتنا الملامسة للأغذية والقابلة لإعادة التدوير لتلبية أهداف الاقتصاد الدائري في الاتحاد الأوروبي، بتركيبات أحادية المادة تدعم الفرز وإعادة التدوير الميكانيكي.',
  'SVHC declarations provided for all grades on request': 'إقرارات SVHC متاحة لجميع الدرجات عند الطلب',
  'Full supply chain traceability documentation': 'وثائق شاملة لتتبّع سلسلة الإمداد',
  'Rapid response — compliance pack within 48 hours': 'استجابة سريعة — حزمة المطابقة خلال 48 ساعة',
  'Recyclable Grades at a Glance': 'الدرجات القابلة لإعادة التدوير في لمحة',
  'FMPE / FMPP Series': 'سلسلتا FMPE / FMPP',
  'CaCO₃ filler — compatible with PE/PP mechanical recycling streams': 'حشو CaCO₃ — متوافق مع مسارات إعادة التدوير الميكانيكي لـ PE/PP',
  'RECYCLABLE': 'قابل لإعادة التدوير',
  'WMB-PE / WMB-PP': 'WMB-PE / WMB-PP',
  'TiO₂ white — stays in polymer matrix during recycling; sortation compatible': 'أبيض TiO₂ — يبقى في مصفوفة البوليمر أثناء إعادة التدوير؛ متوافق مع الفرز',
  'Carbon black — designed for closed-loop agricultural and packaging recycle': 'أسود الكربون — مصمَّم لإعادة التدوير بدورة مغلقة في الزراعة والتغليف',
  'Halogen-free flame retardant — no toxic combustion by-products': 'مثبّط لهب خالٍ من الهالوجين — دون نواتج احتراق سامة',
  'Food-contact grade — EU 10/2011 & FDA compliant': 'درجة ملامسة الأغذية — مطابقة لـ EU 10/2011 وFDA',
  'HALOGEN-FREE': 'خالٍ من الهالوجين',
  'Standards & Certifications': 'المعايير والشهادات',
  'What We Can Document': 'ما يمكننا توثيقه',
  'Full compliance packs are available on request. Contact us with your specific standard or regulatory requirement.':
    'تتوفر حزم مطابقة شاملة عند الطلب. تواصل معنا مع ذكر المعيار أو المتطلب التنظيمي الذي تحتاجه.',
  'EU Regulation 10/2011': 'لائحة الاتحاد الأوروبي 10/2011',
  'Plastic materials and articles intended to contact food': 'المواد والمنتجات البلاستيكية المعدّة لملامسة الأغذية',
  'FDA 21 CFR': 'FDA 21 CFR',
  'United States food-contact compliance for applicable grades': 'مطابقة ملامسة الأغذية في الولايات المتحدة للدرجات المعنية',
  'RoHS / REACH': 'RoHS / REACH',
  'Restriction of hazardous substances in pigments and carriers': 'تقييد المواد الخطرة في الأصباغ والحوامل',
  'CHEMICAL SAFETY': 'السلامة الكيميائية',
  'ISO 14001:2015': 'ISO 14001:2015',
  'Certified environmental management system at our facility': 'نظام إدارة بيئية معتمد في منشأتنا',
  'CERTIFIED': 'معتمد',
  'ISO 9001:2015': 'ISO 9001:2015',
  'Quality management system — consistent, traceable production': 'نظام إدارة الجودة — إنتاج متسق وقابل للتتبّع',
  'SVHC-Free': 'خالٍ من SVHC',
  'No Substances of Very High Concern in standard formulations': 'لا مواد مثيرة للقلق الشديد (SVHC) في التركيبات القياسية',
  'REACH': 'REACH',
  'Get Compliance Documentation': 'احصل على وثائق المطابقة',
  'Need ESG, REACH, or Food-Contact Docs?': 'تحتاج وثائق ESG أو REACH أو ملامسة الأغذية؟',
  "Tell us your grade, volume, and compliance requirement — we'll send the full documentation pack within 48 hours.":
    'أخبرنا بالدرجة والكمية ومتطلب المطابقة — وسنرسل لك حزمة الوثائق الشاملة خلال 48 ساعة.',
  'Request Compliance Pack →': 'اطلب حزمة المطابقة ←',
  'Technical Resources': 'الموارد الفنية',
  'Sustainability': 'الاستدامة',

  // ───────── Compare ─────────
  'Product Comparison': 'مقارنة المنتجات',
  'Compare All Products': 'قارن بين جميع المنتجات',
  'Side-by-side spec comparison across the full Blau Batch portfolio — manufactured Filler grades and the complete Coraplast distributed range.':
    'مقارنة جنباً إلى جنب للمواصفات عبر محفظة بلاو باتش الشاملة — درجات الحشو المصنَّعة لدينا ومجموعة Coraplast الشاملة الموزَّعة.',
  'Specification': 'المواصفات',
  'Details': 'التفاصيل',
  'Request Sample': 'اطلب عيّنة',
  'Sample': 'عيّنة',
  'Filler MB (PE)': 'ماستر باتش الحشو (PE)',
  'PE (LDPE / LLDPE / HDPE)': 'PE (LDPE / LLDPE / HDPE)',
  'Extrusion': 'البثق',
  '1 tonne': 'طن واحد',
  '25 kg bags / FIBC': 'أكياس 25 كجم / FIBC',
  'Packaging': 'التغليف',
  'Filler MB (PP)': 'ماستر باتش الحشو (PP)',
  'PP (Homo PP / Co-PP)': 'PP (هوموبوليمر / كوبوليمر)',
  'Raffia / BOPP': 'رافيا / BOPP',
  'Textiles': 'المنسوجات',
  'White MB': 'ماستر باتش أبيض',
  'DISTRIBUTED': 'موزَّع',
  'PE / PP': 'PE / PP',
  'Pipe Extrusion': 'بثق المواسير',
  'Fibre Spinning': 'غزل الألياف',
  'WMB Standard': 'WMB قياسي',
  'WMB Food': 'WMB لملامسة الأغذية',
  'WMB High-Opacity': 'WMB عالي العتامة',
  'On request': 'عند الطلب',
  '25 kg bags': 'أكياس 25 كجم',
  'Black MB': 'ماستر باتش أسود',
  'BMB Standard': 'BMB قياسي',
  'BMB UV-Pipe': 'BMB للمواسير (مقاوم UV)',
  'BMB Cable': 'BMB للكابلات',
  'Pipes': 'المواسير',
  'Colour MB': 'ماستر باتش ملوّن',
  'CMB Series': 'سلسلة CMB',
  'RAL Standard': 'RAL قياسي',
  'Pantone Match': 'مطابقة Pantone',
  'Custom Development': 'تطوير مخصص',
  'Additive MB': 'ماستر باتش الإضافات',
  'All Processes': 'جميع العمليات',
  'Film': 'الأفلام',
  'Injection': 'الحقن',
  'Fibre': 'الألياف',
  'Slip / Antiblock': 'منزلق / مانع التصاق',
  'Series': 'السلسلة',
  'Supply Type': 'نوع التوريد',
  'Key Processes': 'العمليات الرئيسية',
  'Available Grades': 'الدرجات المتاحة',
  'Min. Order Qty': 'الحد الأدنى للطلب',
  'UV-Stable Grade': 'درجة مقاومة لـ UV',
  'TDS & CoA Provided': 'TDS وCoA مرفقان',
  'ISO 9001-Aligned': 'متوافق مع ISO 9001',
  'Sample Available': 'عيّنات متاحة',

  // ───────── Resources ─────────
  'Request received.': 'تم استلام طلبك.',
  "We'll send your requested documents to": 'سنرسل المستندات التي طلبتها إلى',
  'within 1 business day.': 'خلال يوم عمل واحد.',
  'Selected Documents': 'المستندات المحددة',
  'No documents selected — tick the cards above to add them here.': 'لم يتم تحديد أي مستند — حدّد البطاقات أعلاه لإضافتها هنا.',
  'Your Details': 'بياناتك',
  'Send Me These Documents': 'أرسل لي هذه المستندات',
  'Sent within 1 business day · Saturday–Thursday 9AM–5PM Cairo': 'تُرسل خلال يوم عمل واحد · من السبت إلى الخميس، 9 ص – 5 م بتوقيت القاهرة',
  'Technical Documents': 'المستندات الفنية',
  'Download Library': 'مكتبة التنزيلات',
  "Select the documents you need, then fill in your details below — we'll email everything within 1 business day.":
    'اختر المستندات التي تحتاجها، ثم أدخل بياناتك أدناه — وسنرسل لك كل شيء بالبريد الإلكتروني خلال يوم عمل واحد.',
  'FAQ': 'الأسئلة الشائعة',
  'Frequently Asked Questions': 'الأسئلة الشائعة',
  "Can't find your answer? Contact us directly.": 'لم تجد إجابتك؟ تواصل معنا مباشرة.',
  'Ask a Question': 'اطرح سؤالاً',
  'Terminology': 'المصطلحات',
  'Masterbatch Glossary': 'مسرد مصطلحات الماستر باتش',
  'Technical Blog': 'المدونة التقنية',
  'Technical Articles': 'مقالات تقنية',
  'In-depth guides on masterbatch selection, processing, and applications — written by our compounding team for plastics engineers and procurement professionals.':
    'أدلة معمّقة حول اختيار الماستر باتش ومعالجته وتطبيقاته — أعدّها فريق التركيب لدينا لمهندسي البلاستيك ومتخصصي المشتريات.',
  'Read article': 'اقرأ المقال',
  'Technical Library': 'المكتبة الفنية',
  'Product Documents,': 'مستندات المنتجات،',
  'Guides & FAQs': 'الأدلة والأسئلة الشائعة',
  'Technical data sheets, processing guides, certificates of analysis, and an FAQ covering filler masterbatch selection, dosage, processing, and quality control.':
    'صحائف البيانات الفنية وأدلة المعالجة وشهادات التحليل، إضافةً إلى أسئلة شائعة عن اختيار ماستر باتش الحشو وجرعاته ومعالجته ومراقبة جودته.',
  'Resources': 'الموارد',
  'Request a TDS': 'اطلب صحيفة TDS',
  'View FAQs': 'عرض الأسئلة الشائعة',
  'FMPE Series — Technical Data Sheet': 'سلسلة FMPE — صحيفة البيانات الفنية',
  'TDS': 'TDS',
  'MFI, ash content, moisture, carrier, packaging, and processing guidelines for FMPE-1070, 1075, 1080.': 'MFI ومحتوى الرماد والرطوبة والحامل والتعبئة وإرشادات المعالجة للدرجات FMPE-1070 و1075 و1080.',
  'FMPP Series — Technical Data Sheet': 'سلسلة FMPP — صحيفة البيانات الفنية',
  'MFI, ash content, moisture, carrier, packaging, and processing guidelines for FMPP-1070, 1075, 1080.': 'MFI ومحتوى الرماد والرطوبة والحامل والتعبئة وإرشادات المعالجة للدرجات FMPP-1070 و1075 و1080.',
  'Colour Masterbatch — Product Overview': 'ماستر باتش ملوّن — نظرة عامة على المنتج',
  'Overview': 'نظرة عامة',
  'Carrier compatibility, colour systems, let-down ratios, ΔE tolerance, and food-contact grade availability.': 'توافق الحوامل وأنظمة الألوان ونسب الخلط وتفاوت ΔE وتوفر درجات ملامسة الأغذية.',
  'White Masterbatch — Product Overview': 'ماستر باتش أبيض — نظرة عامة على المنتج',
  'TiO₂-based grades for blown film, injection moulding, and food-contact applications.': 'درجات أساسها TiO₂ لأفلام النفخ والقولبة بالحقن وتطبيقات ملامسة الأغذية.',
  'Black Masterbatch — Product Overview': 'ماستر باتش أسود — نظرة عامة على المنتج',
  'Carbon black grades for PE, PP, and PET — covering UV protection, food contact, and high-loading variants.': 'درجات أسود الكربون لـ PE وPP وPET — تشمل الحماية من UV وملامسة الأغذية والدرجات عالية التحميل.',
  'Additive Masterbatch — Product Overview': 'ماستر باتش الإضافات — نظرة عامة على المنتج',
  'Filler MB Dosage & Processing Guide': 'دليل جرعات ومعالجة ماستر باتش الحشو',
  'Guide': 'دليل',
  'Recommended dosage ranges by application type, temperature profiles, and troubleshooting tips for filler masterbatch.': 'نطاقات الجرعات الموصى بها حسب نوع التطبيق، ومنحنيات الحرارة، ونصائح استكشاف الأخطاء لماستر باتش الحشو.',
  'Full Product Catalogue': 'كتالوج المنتجات الشامل',
  'Catalogue': 'كتالوج',
  'Complete portfolio overview across all Blau Batch product lines — suitable for procurement and product selection.': 'نظرة شاملة على محفظة جميع خطوط منتجات بلاو باتش — مناسبة للمشتريات واختيار المنتجات.',
  'Certificate of Analysis (sample)': 'شهادة التحليل (نموذج)',
  'CoA': 'CoA',
  'Typical CoA format issued with each batch — available for specific batch numbers on request.': 'صيغة نموذجية لشهادة CoA تصدر مع كل تشغيلة — متاحة لأرقام تشغيلات محددة عند الطلب.',
  'What is filler masterbatch and how does it reduce my costs?': 'ما هو ماستر باتش الحشو وكيف يخفّض تكاليفي؟',
  'Filler masterbatch is a concentrated blend of CaCO₃ (calcium carbonate) dispersed in a polymer carrier (PE or PP). By replacing a portion of your virgin polymer with filler masterbatch, you reduce raw material cost while maintaining acceptable mechanical properties. Typical cost savings depend on the price differential between virgin polymer and masterbatch, and the dosage rate used — generally 10–30% substitution in film applications.':
    'ماستر باتش الحشو مزيج مركّز من CaCO₃ (كربونات الكالسيوم) موزَّع في حامل بوليمري (PE أو PP). باستبدال جزء من البوليمر الخام به تخفّض تكلفة المواد الخام مع الحفاظ على خصائص ميكانيكية مقبولة. تعتمد وفورات التكلفة على فرق السعر بين البوليمر الخام والماستر باتش ونسبة الجرعة المستخدمة — وتبلغ عادةً 10–30% استبدالاً في تطبيقات الأفلام.',
  'What is the difference between FMPE and FMPP Series?': 'ما الفرق بين سلسلتي FMPE وFMPP؟',
  'FMPE uses a polyethylene (LDPE/LLDPE/HDPE) carrier and is designed for PE applications: blown film, cast film, extrusion coating, and injection moulding. FMPP uses a polypropylene (PP homopolymer) carrier and is designed for PP applications: raffia tape, non-woven, BOPP film, and PP injection moulding. Using PE carrier in a PP process (or vice versa) can cause processing issues and is not recommended.':
    'تستخدم FMPE حاملاً من البولي إيثيلين (LDPE/LLDPE/HDPE) وهي مصممة لتطبيقات PE: أفلام النفخ والأفلام المصبوبة والطلاء بالبثق والقولبة بالحقن. أما FMPP فتستخدم حاملاً من البولي بروبيلين (هوموبوليمر PP) وهي مصممة لتطبيقات PP: شرائط الرافيا والأقمشة غير المنسوجة وأفلام BOPP والقولبة بالحقن لـ PP. استخدام حامل PE في عملية PP (أو العكس) قد يسبب مشكلات في المعالجة ولا يُنصح به.',
  'What dosage rate should I start with?': 'بأي نسبة جرعة أبدأ؟',
  'We recommend starting at 15% for most blown film applications and adjusting in 5% increments while monitoring mechanical properties (tear, tensile) and optical properties (haze). For raffia and non-woven, start at 10–15% and monitor fibre tenacity. The maximum recommended rate depends on your target properties, line speed, and equipment — contact our technical team for application-specific guidance.':
    'نوصي بالبدء بنسبة 15% في معظم تطبيقات أفلام النفخ، ثم الضبط بزيادات 5% مع مراقبة الخواص الميكانيكية (التمزق والشد) والبصرية (العتامة). وللرافيا والأقمشة غير المنسوجة ابدأ بنسبة 10–15% وراقب متانة الألياف. تعتمد النسبة القصوى الموصى بها على الخواص المستهدفة وسرعة الخط والمعدات — تواصل مع فريقنا الفني للحصول على إرشادات خاصة بتطبيقك.',
  'How is the masterbatch packaged and what is the shelf life?': 'كيف يُعبَّأ الماستر باتش وما مدة صلاحيته؟',
  'Our masterbatch is available in 25 kg PP woven bags (standard) and 500–1000 kg FIBC big bags (for high-volume orders). Shelf life is 24 months from production date when stored in original sealed packaging in a cool, dry environment (below 30°C, away from direct sunlight). Reseal partially used bags immediately to prevent moisture absorption.':
    'يتوفر الماستر باتش لدينا في أكياس PP منسوجة سعة 25 كجم (القياسية) وأكياس FIBC كبيرة سعة 500–1000 كجم (للطلبات الكبيرة). مدة الصلاحية 24 شهراً من تاريخ الإنتاج عند التخزين في العبوة الأصلية المغلقة في مكان بارد وجاف (أقل من 30°م وبعيداً عن أشعة الشمس المباشرة). أعد إغلاق الأكياس المستخدمة جزئياً فوراً لمنع امتصاص الرطوبة.',
  'Can I get a sample before placing a full order?': 'هل يمكنني الحصول على عيّنة قبل تقديم طلب كامل؟',
  "Yes. We offer pre-production samples upon request — typically 5–25 kg quantities for processing trials. Contact us with your polymer type, application, and processing parameters, and we'll advise on which grade to sample and arrange delivery.":
    'نعم. نوفّر عيّنات ما قبل الإنتاج عند الطلب — عادةً بكميات 5–25 كجم لتجارب المعالجة. تواصل معنا مع ذكر نوع البوليمر والتطبيق وظروف المعالجة، وسنوصي بالدرجة المناسبة للعيّنة ونرتّب التسليم.',
  'Do you provide food-contact grade masterbatch?': 'هل توفرون ماستر باتش بدرجة ملامسة الأغذية؟',
  'Yes. Through our Coraplast partnership, we offer white, black, and colour masterbatch grades compliant with EU 10/2011 Regulation and FDA 21 CFR requirements for food contact applications. Request the specific grade and regulatory documentation when enquiring.':
    'نعم. من خلال شراكتنا مع Coraplast نوفّر درجات ماستر باتش أبيض وأسود وملوّن مطابقة للائحة الاتحاد الأوروبي 10/2011 ومتطلبات FDA 21 CFR لتطبيقات ملامسة الأغذية. اذكر الدرجة المطلوبة والوثائق التنظيمية عند الاستفسار.',
  'What quality control tests do you run on each batch?': 'ما اختبارات مراقبة الجودة التي تجرونها على كل تشغيلة؟',
  'Each production batch is tested for: Melt Flow Index (ISO 1133), ash content (ISO 3451), moisture content, colour consistency, and visual dispersibility. A Certificate of Analysis (CoA) is issued for every batch and can be provided alongside each shipment. Full traceability from raw material intake to finished goods is maintained.':
    'يُختبر كل تشغيلة إنتاج لقياس: مؤشر سيولة الانصهار (ISO 1133) ومحتوى الرماد (ISO 3451) ومحتوى الرطوبة وثبات اللون وقابلية التشتت بالفحص البصري. وتصدر شهادة تحليل (CoA) لكل تشغيلة ويمكن إرفاقها مع كل شحنة. ونحافظ على تتبّع شامل من استلام المواد الخام حتى المنتج النهائي.',
  'What is your lead time and minimum order quantity?': 'ما مدة التسليم والحد الأدنى للطلب؟',
  'Calcium Carbonate — the inorganic mineral used as filler. Typically sourced from limestone and surface-treated for improved polymer compatibility.':
    'كربونات الكالسيوم — المعدن غير العضوي المستخدم كحشو. تُستخرج عادةً من الحجر الجيري وتُعالَج سطحياً لتحسين توافقها مع البوليمر.',
  'MFI / MFR': 'MFI / MFR',
  'Melt Flow Index / Melt Flow Rate — measures how easily a polymer flows when melted (g/10min). Higher MFI = easier flow. FMPE tested at 190°C/2.16kg, FMPP at 230°C/2.16kg.':
    'مؤشر سيولة الانصهار / معدل سيولة الانصهار — يقيس سهولة انسياب البوليمر عند انصهاره (غ/10 دقائق). كلما ارتفع MFI كان الانسياب أسهل. تُختبر FMPE عند 190°م/2.16 كجم وFMPP عند 230°م/2.16 كجم.',
  'Let-Down Ratio (LDR)': 'نسبة الخلط (LDR)',
  'The proportion of masterbatch blended into the base resin. A 2% LDR means 2 kg masterbatch per 98 kg of base polymer.':
    'نسبة الماستر باتش المخلوطة مع الراتنج الأساسي. تعني نسبة خلط 2% وجود 2 كجم ماستر باتش لكل 98 كجم من البوليمر الأساسي.',
  'The polymer matrix in which pigment or filler is dispersed. Must be compatible with the end-use resin to avoid processing problems.':
    'المصفوفة البوليمرية التي تتوزع فيها الأصباغ أو الحشو. يجب أن تتوافق مع راتنج الاستخدام النهائي لتجنب مشكلات المعالجة.',
  'ΔE': 'ΔE',
  'Delta-E — a numerical measure of colour difference. ΔE ≤ 1.0 is generally considered imperceptible to the human eye; Blau Batch colour MB targets ΔE ≤ 0.5 batch-to-batch.':
    'Delta-E — مقياس رقمي للفرق اللوني. تُعدّ قيمة ΔE ≤ 1.0 غير محسوسة عموماً للعين البشرية؛ ويستهدف ماستر باتش الملوّن من بلاو باتش ΔE ≤ 0.5 بين التشغيلات.',
  'Technical Data Sheet — document listing all key product specifications, test methods, processing recommendations, and packaging details.':
    'صحيفة البيانات الفنية — مستند يسرد المواصفات الرئيسية للمنتج وطرق الاختبار وتوصيات المعالجة وتفاصيل التعبئة.',
  'Certificate of Analysis — batch-specific document confirming that tested properties meet the product specification.':
    'شهادة التحليل — مستند خاص بكل تشغيلة يؤكد أن الخواص المختبَرة تطابق مواصفات المنتج.',
  'BOPP': 'BOPP',
  'Biaxially Oriented Polypropylene — PP film stretched in both machine and transverse directions for improved stiffness and barrier properties.':
    'البولي بروبيلين ثنائي الاتجاه — فيلم PP يُشدّ في اتجاهي الماكينة والعرض لتحسين الصلابة وخواص الحاجز.',
  'Raffia': 'الرافيا',
  'Flat or fibrillated PP tape produced by slitting and stretching extruded film — used for woven bags, sacks, and geotextiles.':
    'شريط PP مسطّح أو ليفي يُنتَج بتقطيع الفيلم المبثوق وشدّه — يُستخدم للأكياس والجوالات المنسوجة والمنسوجات الجيولوجية.',
  'Select at least one document above.': 'اختر مستنداً واحداً على الأقل أعلاه.',
  'Required.': 'مطلوب.',
  'Something went wrong. Please email info@blaubatch.com directly.': 'حدث خطأ ما. يرجى مراسلتنا مباشرة على info@blaubatch.com.',
  'Filler MB': 'ماستر باتش الحشو',
  'What is Filler Masterbatch and How Does it Reduce Material Costs?': 'ما هو ماستر باتش الحشو وكيف يخفّض تكاليف المواد؟',
  "A complete guide to CaCO₃-based filler masterbatch — how it works, how it's made, and how to calculate cost savings for your specific application.":
    'دليل شامل لماستر باتش الحشو القائم على CaCO₃ — كيف يعمل وكيف يُصنَّع وكيف تحتسب وفورات التكلفة لتطبيقك.',
  'Grade Selection': 'اختيار الدرجة',
  'CaCO₃ Loading: 70% vs 75% vs 80% — Which Grade Is Right for Your Application?': 'تحميل CaCO₃: 70% مقابل 75% مقابل 80% — أي درجة تناسب تطبيقك؟',
  'A technical comparison of high-loading filler grades — covering mechanical property trade-offs, processing considerations, and application fit.':
    'مقارنة تقنية بين درجات الحشو عالية التحميل — تشمل المفاضلة بين الخواص الميكانيكية واعتبارات المعالجة وملاءمة التطبيق.',
  'Processing': 'المعالجة',
  'PE vs PP Carrier Systems: Why Matching Carrier to Base Resin Matters': 'أنظمة الحوامل PE مقابل PP: لماذا تهمّ مطابقة الحامل للراتنج الأساسي',
  'Why using the wrong carrier polymer causes processing problems — and how to select the right filler masterbatch carrier for your production line.':
    'لماذا يسبب استخدام حامل بوليمري غير مناسب مشكلات في المعالجة — وكيف تختار الحامل المناسب لماستر باتش الحشو في خط إنتاجك.',
  'TiO₂ Masterbatch: Understanding Opacity, Whiteness, and Food-Contact Compliance': 'ماستر باتش TiO₂: فهم العتامة والبياض ومطابقة ملامسة الأغذية',
  'How TiO₂ loading affects opacity and CIE whiteness index — and what food-contact compliance (EU 10/2011, FDA) means in practice.':
    'كيف يؤثر تحميل TiO₂ في العتامة ومؤشر البياض CIE — وماذا تعني مطابقة ملامسة الأغذية (EU 10/2011 وFDA) عملياً.',
  'UV Stabilisation in Agricultural Film: What Makes a Masterbatch Last 10+ Years?': 'التثبيت ضد UV في الأفلام الزراعية: ما الذي يجعل الماستر باتش يدوم أكثر من 10 سنوات؟',
  'How HALS-based UV stabilisers in black and additive masterbatch protect agricultural films from photodegradation in MENA and Mediterranean climates.':
    'كيف تحمي مثبّتات UV القائمة على HALS في الماستر باتش الأسود والإضافات الأفلام الزراعية من التحلل الضوئي في مناخ الشرق الأوسط وشمال أفريقيا والبحر المتوسط.',
  'Quality': 'الجودة',
  'Reading a Masterbatch CoA: The 7 Properties Every Buyer Should Check': 'قراءة شهادة CoA للماستر باتش: 7 خواص يجب أن يتحقق منها كل مشترٍ',
  'MFI, ash content, moisture, colour delta-E, and dispersibility — a practical guide to reading a Certificate of Analysis before accepting a shipment.':
    'MFI ومحتوى الرماد والرطوبة وdelta-E اللوني وقابلية التشتت — دليل عملي لقراءة شهادة التحليل قبل استلام الشحنة.',

  // ───────── Full Range campaign page ─────────
  'One Source · Full Spectrum': 'مصدر واحد · حلول شاملة',
  'One Trusted': 'مورّد واحد',
  'Supplier.': 'موثوق.',
  'Blau Batch manufactures Filler Masterbatch in-house and distributes the complete Coraplast range — colour, white, black, and additive — across MENA and Europe. One supplier for every grade your production needs.':
    'تصنّع بلاو باتش ماستر باتش الحشو داخلياً وتوزّع مجموعة Coraplast الشاملة — ملوّن وأبيض وأسود وإضافات — في الشرق الأوسط وشمال أفريقيا وأوروبا. مورّد واحد لكل درجة يحتاجها إنتاجك.',
  'Get a Free Quote': 'احصل على عرض سعر مجاني',
  'Full-Spectrum Supplier': 'مورّد شامل',
  'The Problem': 'المشكلة',
  'Still Juggling Multiple': 'ما زلت تتعامل مع عدة',
  'Masterbatch Suppliers?': 'موردين للماستر باتش؟',
  'Before — Multiple Suppliers': 'قبل — موردون متعددون',
  'With Blau Batch — One Supplier': 'مع بلاو باتش — مورّد واحد',
  'Full Product Range': 'مجموعة المنتجات الشاملة',
  'Six Product Lines. Every Grade': 'ستة خطوط منتجات. كل درجة',
  'Your Production Needs.': 'يحتاجها إنتاجك.',
  'Two in-house manufactured filler grades plus four internationally sourced Coraplast lines — all from one supplier, one contact, one invoice.':
    'درجتا حشو مصنَّعتان داخلياً إضافةً إلى أربعة خطوط Coraplast مستوردة عالمياً — كلها من مورّد واحد وجهة اتصال واحدة وفاتورة واحدة.',
  'View Product': 'عرض المنتج',
  'Request Pricing for Any Grade': 'اطلب التسعير لأي درجة',
  'Industries Served': 'الصناعات التي نخدمها',
  'Built for Plastics': 'مصمَّمة لمصنّعي',
  'Processors Everywhere.': 'البلاستيك في كل مكان.',
  'From blown film to pipe extrusion — we supply the right grades across 8 major industries.': 'من أفلام النفخ إلى بثق المواسير — نوفّر الدرجات المناسبة عبر 8 صناعات رئيسية.',
  'Why Blau Batch': 'لماذا بلاو باتش',
  'The Single-Source Advantage': 'ميزة المصدر الواحد',
  'How It Works': 'كيف نعمل',
  'From Enquiry to Delivery': 'من الاستفسار إلى التسليم',
  'in 3 Simple Steps': 'في 3 خطوات بسيطة',
  'Start Your Enquiry Now': 'ابدأ استفسارك الآن',
  'Request a Free Quote': 'اطلب عرض سعر مجاني',
  "Let's Talk": 'لنتحدث عن',
  'Production.': 'إنتاجك.',
  "Separate QC checks for every supplier's material": 'فحوص جودة منفصلة لمواد كل مورّد',
  "Every additional vendor adds complexity, inconsistency, and hidden cost to your production line. There's a better way.": 'كل مورّد إضافي يضيف تعقيداً وتفاوتاً وتكلفة خفية إلى خط إنتاجك. هناك طريقة أفضل.',
  'All specs subject to grade. Contact our technical team for detailed TDS or custom formulation enquiries.': 'جميع المواصفات تتبع الدرجة. تواصل مع فريقنا الفني للحصول على TDS تفصيلية أو للاستفسار عن التركيبات المخصصة.',
  'UV stabilisers, antioxidants, anti-block, slip, anti-static, and combination additive grades.': 'مثبّتات UV ومضادات الأكسدة ومانعات الالتصاق والمنزلقات ومضادات الكهرباء الساكنة ودرجات الإضافات المركّبة.',
  'Tell us your polymer, application, and volume. Our team responds within 24 hours with a grade recommendation and competitive pricing.':
    'أخبرنا بنوع البوليمر والتطبيق والكمية. يردّ فريقنا خلال 24 ساعة بتوصية بالدرجة المناسبة وأسعار تنافسية.',
  'Quote Request Sent': 'تم إرسال طلب عرض السعر',
  'Our technical team will respond within 24 hours with grade recommendations and competitive pricing.': 'سيردّ فريقنا الفني خلال 24 ساعة بتوصيات الدرجات وأسعار تنافسية.',
  'Also WhatsApp Us': 'راسلنا أيضاً عبر واتساب',
  'Get Your Quote': 'احصل على عرض السعر',
  "Fill in your details and we'll respond within 24 hours.": 'أدخل بياناتك وسنردّ خلال 24 ساعة.',
  'What are you looking for?': 'ماذا تبحث عنه؟',
  'Full Name *': 'الاسم الكامل *',
  'Company *': 'الشركة *',
  'Email *': 'البريد الإلكتروني *',
  'Phone / WhatsApp *': 'الهاتف / واتساب *',
  'Country': 'الدولة',
  'Application note': 'ملاحظة عن التطبيق',
  'Filler': 'الحشو',
  'White': 'الأبيض',
  'Black': 'الأسود',
  'Colour': 'الملوّن',
  'Additive': 'الإضافات',
  'CaCO₃-based filler in LDPE/LLDPE carrier. 60–80% loading. Blown film, bags, and general extrusion.': 'حشو أساسه CaCO₃ على حامل LDPE/LLDPE. تحميل 60–80%. للأفلام المنفوخة والأكياس والبثق العام.',
  '60–80% CaCO₃': '60–80% CaCO₃',
  'LDPE/LLDPE Carrier': 'حامل LDPE/LLDPE',
  'Blown Film & Extrusion': 'أفلام النفخ والبثق',
  'CaCO₃-based filler in PP homopolymer carrier. BOPP, raffia, woven sacks, and PPR pipe.': 'حشو أساسه CaCO₃ على حامل هوموبوليمر PP. لأفلام BOPP والرافيا والجوالات المنسوجة ومواسير PPR.',
  '60–75% CaCO₃': '60–75% CaCO₃',
  'BOPP / Raffia / Pipe': 'BOPP / رافيا / مواسير',
  'WHITE': 'أبيض',
  'CORAPLAST': 'CORAPLAST',
  'TiO₂-based white in PE and PET carriers. High opacity, food-contact compliant grades available.': 'أبيض أساسه TiO₂ على حوامل PE وPET. عتامة عالية وتتوفر درجات مطابقة لملامسة الأغذية.',
  'TiO₂ Pigment': 'صبغة TiO₂',
  'PE / PET Carrier': 'حامل PE / PET',
  'BLACK': 'أسود',
  'Carbon black concentrates for pipe, film, cable, and technical moulding. UV-protective grades.': 'مركّزات أسود الكربون للمواسير والأفلام والكابلات والقولبة التقنية. درجات واقية من UV.',
  'UV Protective': 'واقٍ من UV',
  'Pipe / Cable / Film': 'مواسير / كابلات / أفلام',
  'COLOUR': 'ملوّن',
  'Full Pantone/RAL spectrum. Custom colour match and standard catalogue grades for all polymers.': 'نطاق Pantone/RAL شامل. مطابقة ألوان مخصصة ودرجات كتالوج قياسية لجميع البوليمرات.',
  'Full Colour Range': 'مجموعة ألوان شاملة',
  'Custom Match': 'مطابقة مخصصة',
  'PE / PP / PET / ABS': 'PE / PP / PET / ABS',
  'UV stabilisers, slip/antiblock, anti-static, optical brighteners, and flame retardant grades.': 'مثبّتات UV ومنزلقات/مانعات التصاق ومضادات الكهرباء الساكنة ومبيّضات ضوئية ودرجات مثبّطة للهب.',
  'UV / Slip / OB / FR': 'UV / منزلق / OB / FR',
  'PE / PP Carrier': 'حامل PE / PP',
  'Agricultural & Technical': 'زراعي وتقني',
  'Filler, colour, white & slip for blown film, bags, closures': 'حشو وألوان وأبيض ومنزلق لأفلام النفخ والأكياس والأغطية',
  'Carbon black & CaCO₃ for HDPE, PPR, and PVC extrusion': 'أسود الكربون وCaCO₃ لبثق HDPE وPPR وPVC',
  'UV-stabilised grades for mulch, greenhouse & irrigation film': 'درجات مثبَّتة ضد UV لأفلام المالش والبيوت المحمية والري',
  'Colour & filler for PP non-woven and filament spinning': 'ألوان وحشو للأقمشة غير المنسوجة من PP وغزل الخيوط',
  'Geomembrane and waterproofing sheet compounds': 'مركّبات الأغشية الجيولوجية وألواح العزل المائي',
  'Carbon black & flame retardant for cable jacketing': 'أسود الكربون ومثبّط اللهب لأغلفة الكابلات',
  'Engineered concentrates for interior & exterior parts': 'مركّزات هندسية للأجزاء الداخلية والخارجية',
  'Food-contact colour for caps, closures & housewares': 'ألوان ملامسة الأغذية للأغطية والإغلاقات والأدوات المنزلية',
  'In-House Manufacturer': 'مُصنِّع بإنتاج ذاتي',
  'Own production in 6th of October — full process control, QC, and batch traceability on every run.': 'إنتاج ذاتي في مدينة 6 أكتوبر — تحكّم كامل في العملية ومراقبة جودة وتتبّع لكل تشغيلة.',
  'Authorised Coraplast Distributor': 'موزّع معتمد لشركة Coraplast',
  'Direct distribution partnership — colour, white, black, additive and specialty grades shipped across MENA & Europe.': 'شراكة توزيع مباشرة — درجات الألوان والأبيض والأسود والإضافات والدرجات الخاصة تُشحن إلى الشرق الأوسط وشمال أفريقيا وأوروبا.',
  'Technical Partnership': 'شراكة تقنية',
  'Custom formulation support, application engineering, and real production problem-solving with your team.': 'دعم في التركيبات المخصصة وهندسة التطبيقات وحلّ مشكلات الإنتاج الفعلية مع فريقك.',
  'Certified Quality per Batch': 'جودة معتمدة لكل تشغيلة',
  'TDS and Certificate of Analysis issued per shipment. MFI, ash, colour, and dispersion tested every run.': 'تصدر TDS وشهادة التحليل مع كل شحنة. ويُختبر MFI والرماد واللون والتشتت في كل تشغيلة.',
  'Fast Lead Times': 'مدد تسليم سريعة',
  'Core filler grades in stock. Specialty grades on established trade lanes — no surprises, no delays.': 'درجات الحشو الأساسية متوفرة بالمخزون. والدرجات الخاصة عبر مسارات تجارية راسخة — دون مفاجآت أو تأخير.',
  'Flexible MOQs': 'حدود دنيا مرنة للطلب',
  'Trial quantities available. Scale from sample to full production volumes with consistent pricing.': 'كميات تجريبية متاحة. انتقل من العيّنة إلى كميات الإنتاج الكاملة بأسعار ثابتة.',
  'Multiple Products': 'منتجات متعددة',
  'Not Sure — Need Advice': 'لست متأكداً — أحتاج إلى مشورة',
  'Product Lines': 'خطوط المنتجات',
  'Grades Available': 'الدرجات المتاحة',
  'Quote Response': 'الرد على عرض السعر',
  'MENA & Europe Supply': 'توريد للشرق الأوسط وشمال أفريقيا وأوروبا',
  'TDS + CoA Every Batch': 'TDS وCoA لكل تشغيلة',
  '24h Quote Response': 'رد على عرض السعر خلال 24 ساعة',
  'Multiple accounts, invoices, and contacts to manage': 'حسابات وفواتير وجهات اتصال متعددة يجب إدارتها',
  'Inconsistent quality standards between vendors': 'معايير جودة غير متسقة بين الموردين',
  '2–4 week delays on specialty or imported grades': 'تأخير من 2 إلى 4 أسابيع في الدرجات الخاصة أو المستوردة',
  'Price negotiations spread across 3–5 companies': 'تفاوض على الأسعار موزَّع بين 3 إلى 5 شركات',
  'No single point of technical accountability': 'لا جهة واحدة مسؤولة فنياً',
  'One account, one invoice, one relationship': 'حساب واحد وفاتورة واحدة وعلاقة واحدة',
  'Consistent quality standards across all grades': 'معايير جودة متسقة في جميع الدرجات',
  'Stock held locally — fast delivery on core grades': 'مخزون محلي — تسليم سريع للدرجات الأساسية',
  'TDS + CoA provided on every shipment, every time': 'TDS وCoA مع كل شحنة وفي كل مرة',
  'Volume pricing across your full masterbatch spend': 'أسعار الكميات على كامل إنفاقك على الماستر باتش',
  'One technical team accountable for your production': 'فريق فني واحد مسؤول عن إنتاجك',
  'Send Your Requirement': 'أرسل متطلباتك',
  'Tell us your polymer, application, and monthly volume. Takes 2 minutes via form or WhatsApp.': 'أخبرنا بنوع البوليمر والتطبيق والكمية الشهرية. يستغرق دقيقتين عبر النموذج أو واتساب.',
  'Grade Recommendation': 'توصية بالدرجة المناسبة',
  'Our technical team responds within 24 hours with the right grade, TDS, and competitive pricing.': 'يردّ فريقنا الفني خلال 24 ساعة بالدرجة المناسبة وTDS وأسعار تنافسية.',
  'Sample or Full Order': 'عيّنة أو طلب كامل',
  'Start with a trial quantity at no minimum. Scale to full production with no disruption.': 'ابدأ بكمية تجريبية دون حد أدنى. ثم انتقل إلى الإنتاج الكامل دون انقطاع.',
  'Grade recommendation tailored to your process': 'توصية بالدرجة مصمَّمة لعمليتك',
  'Competitive pricing with flexible MOQs': 'أسعار تنافسية وحدود دنيا مرنة للطلب',
  'Technical data sheets for every grade': 'صحائف بيانات فنية لكل درجة',
  'Sample availability for trial runs': 'عيّنات متاحة للتجارب',
  'Dedicated account manager from day one': 'مدير حساب مخصص منذ اليوم الأول',
  'Blau Batch masterbatch products': 'منتجات ماستر باتش من بلاو باتش',
  'Egypt, UAE, KSA...': 'مصر، الإمارات، السعودية...',
  'E.g. blown film, 30% filler...': 'مثال: أفلام نفخ، حشو 30%...',
  'Your name': 'اسمك',
  'Company name': 'اسم الشركة',
  'Sending…': 'جارٍ الإرسال…',
  'Submit Quote Request': 'إرسال طلب عرض السعر',
}

export default pagesExtra
